title: Learning Curve - Github edition
author: Nick Williams
email: your-n82williams@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am doing Microsoft training for Azure and Github training for DevOps to further my career path. 

# social links
twitter_username: Twitter what
github_username:  n82williams
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
